export const POPUP = {
    EXIT_POPUP: {
        display: true,
        type: "exit",
        title: "Thoát form thông tin",
        showWarning: true,
        warningIconColor: "#ffbb00",
        popupContent: "Bạn có chắc muốn thoát hay không?",
        showCloseBtn: true,
        closeBtn: "Tiếp tục nhập",
        confirmBtn: "Thoát",
        confirmColor: "#ffbb00",
    },
    UPDATE_POPUP: {
        display: true,
        type: "update",
        title: "Lưu bản ghi",
        showWarning: true,
        warningIconColor: "#01B075",
        popupContent: "Bạn có chắc muốn sửa đổi bản ghi không?",
        showCloseBtn: true,
        closeBtn: "Tiếp tục nhập",
        confirmBtn: "Lưu",
        confirmColor: "#01B075",
    },
    CREATE_NEW_POPUP: {
        display: true,
        type: "create",
        title: "Lưu bản ghi",
        showWarning: true,
        warningIconColor: "#01B075",
        popupContent: "Bạn có chắc muốn thêm mới bản ghi không?",
        showCloseBtn: true,
        closeBtn: "Tiếp tục nhập",
        confirmBtn: "Lưu",
        confirmColor: "#01B075",
    },
    DELETE_POPUP: {
        display: true,
        type: "delete",
        title: "Xoá bản ghi",
        showWarning: true,
        warningIconColor: "#F65454",
        popupContent: "Bạn có chắc muốn xoá bản ghi này?",
        showCloseBtn: true,
        closeBtn: "Huỷ",
        confirmBtn: "Xoá",
        confirmColor: "#F65454",
    },
};
